### PR TITLE
Fix some LG, AG in Germany

### PR DESCRIPTION
**Pull request by zuphilip**
(That finishes the checks I wanted to do. The source I used is https://de.wikipedia.org/wiki/Liste_deutscher_Gerichte .)

### CODE REVIEW

**Comment by zuphilip** [comment]
Sorry, I couldn't rebase before the PR because of #10. Maybe, you can cherry-pick just the last commit?

**Comment by fbennett** [comment]
Yep, I'll pick that out. Sorry for the abrupt rebase in the pull - I'm not
the world's greatest git jockey.

Thanks so much for these fixes. The spelling errors are obviously just due
to my ignorance of the language. Are the structural fixes from personal
knowledge, or are you working from a data source?

(I ask because this is part of a larger project that I'm assisting with,
that will ultimately produce identifiers for 13 more European
jurisdictions. If we can streamline the workflow and improve accuracy, it
will be a big win.)

**Comment by zuphilip** [comment]
I was relying on https://de.wikipedia.org/wiki/Liste_deutscher_Gerichte and split the information in your data accordingly for checking with
```
grep -ri 'verfassungs\|staats' data/courts/de/
grep -ri landesgericht data/courts/de/
grep -ri landgericht data/courts/de/baden.wurttemberg/
grep -ri amtsgericht data/courts/de/baden.wurttemberg/karlsruhe/
...
grep -ri finanz data/courts/de/
grep -ri sozial data/courts/de/
grep -ri verwaltung data/courts/de/
```
The cases with differences I checked a little further in Wikipedia, but it seemed that that list was always right. Some geographical labels looked different as well especially the ones with some brackets e.g. `Frankfurt (Oder)` or some composition like `Hof/Saale`, `Bad ...`, `St. ...`. However, most of the times I leaved it as it was in your data and concentrated on the completeness and the structure.

I can possibly help with the other German speaking countries CH, AT as well.

**Comment by fbennett** [comment]
All cherry-picked to master.

**Pull request closed without merging**
